### PR TITLE
Fix typo in Specs section of README.md

### PR DESCRIPTION
**Pull request by jaydeesimon**

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks! Can you wrap it at 70 chars and change `Fixing` to `Fix` in the commit message?

**Comment by jaydeesimon** [comment]
Let me know if this is ok. If you were wondering why I closed it, that was an accident. 😄

**Comment by weavejester** [comment]
No problem! Can you squash your commits and discard the "Wrap it to 70 chars" message? Then I'll merge.

**Comment by jaydeesimon** [comment]
Ok, I think that should do it.

**Comment by weavejester** [comment]
Thanks!

**Pull request merged**
